# Site
name: "Echoes of Zen"
title: "Echoes of Zen"
description: "Inspired by Zen, created by ChatGPT"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
#baseurl: /mediumish-theme-jekyll
google_analytics: 'G-PW320MSKCQ'
disqus: 'echoesofzen'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Fraser:
    name: Fraser
    display_name: Fraser
    gravatar: 498c20b8d93ee0ff7b071340f2a8fc90
    email: fraser.scott@gmail.com
    description: "Creator of Echoes of Zen"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
  toc_levels: 1,2

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
